services:
  web:
    build: 
      context: ./cattainer-web 
    ports:
      - "5000:5000" 
    volumes:
      - ./cattainer-data:/usr/local/app/data 
      #Map the cattainer-data/static folder into a folder just called static in the app directory since flask only knows how to use /static/
      - ./cattainer-data/static:/usr/local/app/static
    
    restart: unless-stopped
