wget https://github.com/feranick/libedgetpu/releases/download/16.0TF2.19.1-1/libedgetpu-dev_16.0tf2.19.1-1.bookworm_arm64.deb
dpkg -i libedgetpu-dev_16.0tf2.19.1-1.bookworm_arm64.deb
apt-get install -f -y
rm libedgetpu-dev_16.0tf2.19.1-1.bookworm_arm64.deb
